/*
10. VISULIZAR LOS APELLIDOS DE LOS VENDEDORES, SU FECHA Y SU NUMERO DE GRUPO, ORDENADOR POR FECHA DESCENDENTE, MOSTRAR LOS 4 ULTIMOS

*/

SELECT apellidos, fecha, grupo_id from vendedores ORDER BY fecha DESC LIMIT 4;