/*
6. VISUALIZAR EL NOMBRE Y LOS APELLIDOS DE LOS VENDEDORES EN UNA MISMA COLUMNA, SU FECHA DE REGISTRO 
Y EL DIA DE LA SEMANA EN LA QUE SE REGISTRARON.
*/

SELECT CONCAT(nombre,' ',apellidos) AS 'Vendedor', fecha, DAYNAME(fecha) AS 'Dia de la semana' FROM vendedores; 